kind: pipeline
name: default
#
steps:
- name: submodules
  image: docker:git
  commands:
  - git checkout $DRONE_COMMIT
  - git submodule init
  - git submodule update --recursive --remote
- name: build
  image: localhost:5000/ubuntu-16.04
  commands:
    - autoconf
    - autoheader    
    - ./configure
    - make
#    - timestamp=$(date '+%Y-%m-%d')
    - filename="dropbear-github-${DRONE_COMMIT:1:8}.tar.gz"
    - tar czf "$filename" dropbear dbclient dropbearconvert
    - mkdir github
    - mv $filename ./github/
    - ls -l ./github
- name: scp
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: scp_host
    port:
      from_secret: scp_port
    username: root
    key:
      from_secret: agent_ssh_key
    target: /root/var/www/
    source: ./github/*
